apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-conf-nginx
  namespace: sirius
data:
  default.conf.template: |
    server {
      listen 80;

      location /api {
        proxy_pass http://localhost:7001; 
      }

      location /info {
        proxy_pass http://localhost:7023; 
      }

      location /login {
        proxy_pass http://localhost:7058; 
      }
    }
